

services:

  menu_db:
    image: postgres:16
    container_name: menu_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 30s
      timeout: 10s
      retries: 50
    restart: always

  menu_app:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    container_name: menu_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/opt/app/static/
    depends_on:
      menu_db:
        condition: service_healthy

        
  nginx:
    image: nginx:1.19.3
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/var/www/static/
    depends_on:
      - menu_app
    ports:
      - "80:80"

volumes:
  pg_volume:
  static_volume: